CC = gcc
CFLAGS = -Wall -Wextra -std=c99
LIBS = -lmpg123

TARGET = mp3_player
SRCS = mp3_player.c

.PHONY: all clean

all: $(TARGET)

$(TARGET): $(SRCS)
    $(CC) $(CFLAGS) $(SRCS) -o $(TARGET) $(LIBS)

clean:
    rm -f $(TARGET)

